### ISSUE TITLE
Plugin bootstrap causes problems with phpunit

### ISSUE THREAD

**Issue by vmikhav** [cakephp/queue#67]
Test contains `\Cake\TestSuite\IntegrationTestTrait::get`. `pluginBootstrap` executed at least twice. It makes the plugin think that the new config was sent by mistake. Is there any workaround or only one way is to exclude the plugin?

```
Possibly related to BadMethodCallException: "Cannot reconfigure existing key `default`"
#0 /var/www/html/vendor/cakephp/queue/src/QueueManager.php(86): Cake\Queue\QueueManager::setConfig('default', Array)
#1 /var/www/html/vendor/cakephp/queue/src/Plugin.php(52): Cake\Queue\QueueManager::setConfig(Array)
#2 /var/www/html/vendor/cakephp/cakephp/src/Http/BaseApplication.php(182): Cake\Queue\Plugin->bootstrap(Object(App\Application))
#3 /var/www/html/vendor/cakephp/cakephp/src/Http/Server.php(111): Cake\Http\BaseApplication->pluginBootstrap()
#4 /var/www/html/vendor/cakephp/cakephp/src/Http/Server.php(79): Cake\Http\Server->bootstrap()
#5 /var/www/html/vendor/cakephp/cakephp/src/TestSuite/MiddlewareDispatcher.php(142): Cake\Http\Server->run(Object(Cake\Http\ServerRequest))
#6 /var/www/html/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php(476): Cake\TestSuite\MiddlewareDispatcher->execute(Array)
#7 /var/www/html/vendor/cakephp/cakephp/src/TestSuite/IntegrationTestTrait.php(362): App\Test\TestCase\Controller\PagesControllerTest->_sendRequest('/', 'GET')
#8 /var/www/html/tests/TestCase/Controller/PagesControllerTest.php(41): App\Test\TestCase\Controller\PagesControllerTest->get('/')
#9 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(1527): App\Test\TestCase\Controller\PagesControllerTest->testMultipleGet()
#10 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(1133): PHPUnit\Framework\TestCase->runTest()
#11 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php(722): PHPUnit\Framework\TestCase->runBare()
#12 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestCase.php(885): PHPUnit\Framework\TestResult->run(Object(App\Test\TestCase\Controller\PagesControllerTest))
#13 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(678): PHPUnit\Framework\TestCase->run(Object(PHPUnit\Framework\TestResult))
#14 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(678): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#15 /var/www/html/vendor/phpunit/phpunit/src/Framework/TestSuite.php(678): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#16 /var/www/html/vendor/phpunit/phpunit/src/TextUI/TestRunner.php(670): PHPUnit\Framework\TestSuite->run(Object(PHPUnit\Framework\TestResult))
#17 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(143): PHPUnit\TextUI\TestRunner->run(Object(PHPUnit\Framework\TestSuite), Array, Array, true)
#18 /var/www/html/vendor/phpunit/phpunit/src/TextUI/Command.php(96): PHPUnit\TextUI\Command->run(Array, true)
#19 /var/www/html/vendor/phpunit/phpunit/phpunit(92): PHPUnit\TextUI\Command::main()
#20 {main}
```

**Comment by vmikhav** [comment]
For now solved it in that way:
```php
    public function pluginBootstrap(): void
    {
        /** @var BasePlugin $plugin */
        foreach ($this->plugins->with('bootstrap') as $plugin) {
            // bootstrap Queue plugin only once
            if ($plugin->getName() == 'Cake/Queue' && !empty(QueueManager::getConfig('default'))) {
                continue;
            }
            $plugin->bootstrap($this);
        }
    }
```
